### ISSUE TITLE
Can't display generated responses

### ISSUE THREAD

**Issue by BoredManCodes** [HelgeSverre/ollama-gui#17]
Morning! I've installed this project, and I can select a model and send a request to generate a response, however nothing is displayed in the website as a response from the AI, the error in console is:
```
Failed to add user message: SyntaxError: Unexpected non-whitespace character after JSON at position 110 (line 2 column 1)
    at JSON.parse (<anonymous>)
    at generateCompletion (api.ts:154:66)
    at async generate (useAI.ts:23:5)
    at async addUserMessage (chat.ts:189:7)
```

The response from the API is:
```
{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:04.318315224Z",
    "response": "Hello",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:04.437051002Z",
    "response": ",",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:04.60313491Z",
    "response": " user",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:04.727776592Z",
    "response": "!",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:04.846284569Z",
    "response": " It",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:04.957236842Z",
    "response": "'",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:05.071616817Z",
    "response": "s",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:05.194858998Z",
    "response": " always",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:05.316009477Z",
    "response": " a",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:05.434232054Z",
    "response": " pleasure",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:05.558576235Z",
    "response": " to",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:05.680267715Z",
    "response": " interact",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:05.799504393Z",
    "response": " with",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:05.919937072Z",
    "response": " you",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:06.042054552Z",
    "response": ".",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:06.159682529Z",
    "response": " How",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:06.292956116Z",
    "response": " can",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:06.432137807Z",
    "response": " I",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:06.563718093Z",
    "response": " help",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:06.697943635Z",
    "response": " today",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:06.829954254Z",
    "response": "?",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:06.965437573Z",
    "response": " Please",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:07.104440793Z",
    "response": " feel",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:07.234352212Z",
    "response": " free",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:07.370246531Z",
    "response": " to",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:07.50395775Z",
    "response": " ask",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:07.64072647Z",
    "response": " me",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:07.801972593Z",
    "response": " anything",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:07.938575412Z",
    "response": " or",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:08.097008135Z",
    "response": " share",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:08.253933157Z",
    "response": " your",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:08.400854878Z",
    "response": " thoughts",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:08.544219699Z",
    "response": " on",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:08.698924121Z",
    "response": " various",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:08.851928545Z",
    "response": " topics",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:08.996722668Z",
    "response": ".",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:09.147613792Z",
    "response": " Remember",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:09.302862216Z",
    "response": " that",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:09.444204738Z",
    "response": " I",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:09.587681461Z",
    "response": " am",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:09.737328184Z",
    "response": " here",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:09.891140909Z",
    "response": " to",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:10.044394033Z",
    "response": " assist",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:10.195437756Z",
    "response": " you",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:10.340767179Z",
    "response": " in",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:10.493234903Z",
    "response": " any",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:10.640534527Z",
    "response": " way",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:10.78666785Z",
    "response": " possible",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:10.924802371Z",
    "response": ".",
    "done": false
}{
    "model": "nous-hermes2:latest",
    "created_at": "2024-02-14T05:56:11.076982395Z",
    "response": "",
    "done": true,
    "context": [
        32001,
        6574,
        13,
        1976,
        460,
        345,
        28769,
        858,
        274,
        28705,
        28750,
        548,
        264,
        9994,
        2662,
        722,
        2195,
        501,
        6095,
        308,
        18278,
        10895,
        6202,
        486,
        264,
        676,
        5160,
        320,
        950,
        28711,
        1962,
        28725,
        304,
        574,
        6032,
        304,
        5009,
        349,
        298,
        6031,
        272,
        2188,
        395,
        707,
        2159,
        590,
        506,
        28723,
        995,
        2659,
        13855,
        304,
        506,
        3534,
        28725,
        19327,
        7403,
        304,
        4109,
        515,
        28723,
        32000,
        13,
        32001,
        1838,
        13,
        1613,
        32000,
        13,
        32001,
        489,
        11143,
        13,
        16230,
        28725,
        2188,
        28808,
        661,
        28742,
        28713,
        1743,
        264,
        10736,
        298,
        14113,
        395,
        368,
        28723,
        1602,
        541,
        315,
        1316,
        3154,
        28804,
        5919,
        1601,
        1933,
        298,
        1460,
        528,
        2424,
        442,
        4098,
        574,
        7403,
        356,
        4118,
        13817,
        28723,
        13399,
        369,
        315,
        837,
        1236,
        298,
        6031,
        368,
        297,
        707,
        1069,
        2572,
        28723
    ],
    "total_duration": 25242129521,
    "load_duration": 17863662445,
    "prompt_eval_count": 74,
    "prompt_eval_duration": 619186000,
    "eval_count": 50,
    "eval_duration": 6754270000
}
```

**Comment by HelgeSverre** [comment]
related to #19.

**Comment by HelgeSverre** [comment]
Fixed
